version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    assignees:
      - "{{ cookiecutter.github_username }}"
    reviewers:
      - "{{ cookiecutter.github_username }}"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    assignees:
      - "{{ cookiecutter.github_username }}"
    reviewers:
      - "{{ cookiecutter.github_username }}"
    schedule:
      interval: weekly
      day: monday
