version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "{{ cookiecutter.github_username }}"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    reviewers:
      - "{{ cookiecutter.github_username }}"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "{{ cookiecutter.github_username }}"
